### ISSUE TITLE
Messaging frequency?

### ISSUE THREAD

**Issue by araujokth** [ColumbiaCGUI/MercuryMessaging#1]
Hi,

Great work on this messaging framework. I was reading both your papers at CHI and UIST and was wondering what is the frequency you transmit in your applications, and what is the maximum frequency you have tested the messaging framework? In the UIST paper you wrote that you can go beyond the 29 Hz of UNET, but I could not see any information on the rates you used in each of the papers.

Thanks!

**Comment by araujokth** [comment]
Ah ok. I thought you were relying on another transport interface that was not UNET. Sorry for the misunderstanding. But once you go above 30 Hz, dont you get a lot of message bursts? I raised that issue here in the Unity Forum https://forum.unity.com/threads/unet-communication-problem-message-arrival-interval-not-consistent-and-burst-arrival.586468/. Even with the low level UNET implementation, once I go to 60 Hz, then you get very inconsistent packet receptions as most of the packets arrive in a burst and couldnt achieve frequencies above 30 Hz with UNET.

**Comment by ce2236** [comment]
We do get some bursts. I took a look at the thread you posted and my result was mostly the same (as your post from today). With some of our recent networking tests we were getting intermittent bursts, but they didn't last long. We also adjusted the network configuration (for the NetworkManager) in those tests. However, I did notice a difference (up to early 2018, so this may have changed) between performance when testing a custom NetworkManager vs a configuration provided to the default NetworkManager. There seemed to be a hidden set of rules as to when you could actually provide the initialization parameters. In aabramychev's response in that thread, he appears to use a custom NetworkManager. And changing the QOS settings seemed to make a large difference the last time I tested it (Spring 2018).
