### ISSUE TITLE
Basic networking with Mercury

### ISSUE THREAD

**Issue by araujokth** [ColumbiaCGUI/MercuryMessaging#2]
Hi,

I was interested in the networking feature with Mercury and had time now to test this. I just noticed that the tutorial on how to use Mercury in a networked scenario is not yet available https://github.com/ColumbiaCGUI/MercuryMessaging/wiki/Tutorial-5:-Basic-networking-with-Mercury. Do you have any plans when to make this available? Thanks again!

**Comment by benplus1** [comment]
As of the current date, the networking tutorial has been updated for LTS 2022 as well as additional VR tutorials with Photon Fusion.
